### ISSUE TITLE
Custom namespace is set but calls cert-manager webhook in default namespace

### ISSUE THREAD

**Issue by SalaryTheft** [its4u/cert-manager-routes-controller#35]
I can see cert-manager namespace is correctly set in cert-manager-routes-controller deployment:

![image](https://github.com/its4u/cert-manager-routes-controller/assets/72844671/f25e1347-8006-4d99-afdb-35a841c30281)

But it still looking for cert-manager webhook in default `cert-manager` namespace.
```
Finished dev [unoptimized + debuginfo] target(s) in 0.31s
Running `target/debug/cert-manager-routes-controller`
ERR; action=Patch; reason=MissingCertificate; note=Some("Error creating Certificate `openshift-operators/gitlab.company.com-cert` requested by Route `company/gitlab`: ApiError: Internal error occurred: failed calling webhook \"webhook.cert-manager.io\": failed to call webhook: Post \"https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s\": service \"cert-manager-webhook\" not found: InternalError (ErrorResponse { status: \"Failure\", message: \"Internal error occurred: failed calling webhook \\\"webhook.cert-manager.io\\\": failed to call webhook: Post \\\"https://cert-manager-webhook.cert-manager.svc:443/mutate?timeout=10s\\\": service \\\"cert-manager-webhook\\\" not found\", reason: \"InternalError\", code: 500 })");
```

**Comment by poponealex** [comment]
Hi @SalaryTheft! 

This is not an issue related to the controller's deployment NS. You are encountering this error because `cert-manager` is not properly deployed. `cert-manager-routes-controller` doesn't call the `cert-manager`'s API, it simply creates `Certificate` instances that are watched and controlled by `cert-manager` itself. 

What version of Openshift are you running? How come is your cert-manager install in the openshift-operators NS and not running in  a custom NS? Are you using the cert-manager community Operator or the cert-manager Operator for RedHat Openshift?

**Comment by SalaryTheft** [comment]
Thanks for your quick response. 

I'm using OpenShift 4.12 and cert-manager community operator. It didn't give me option to select NS, defaulted to openshift-operators NSz

I've switched to 'cert-manager for RHOCP'. I didn't tried the cert-manager-routes-controller with it but I'm pretty sure it will work.
